# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: James Stone
markdown: kramdown
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "README.md"]
email: jamesdanstone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  James Stone designs and animates things for humans.
url: "https://jamesdanstone.github.io/Portfolio-Project/" # the base hostname & protocol for your site, e.g. http://example.com
author: James Stone

# More SEO stuff
webmaster_verifications:
  # google:

#social links

instagram: https://www.instagram.com/jamesdanstone/
linkedin: https://www.linkedin.com/in/james-stone-3a9907b2/

#logo
logo: james_stone_logo.svg

image_path: assets/img/
